name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate samples index file
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: samples/schema.json
          INPUT_JSONS: samples/index.json

      - name: Validate samples
        run: |
          samples=$(jq '.samples[] | @base64') <<< samples/index.json
          for sample_b64 in ${plans}; do
            _jq() {
                echo "${sample_b64}" | base64 --decode | jq -r "$1"
            }
            sample_id=$(_jq '.id')
            if [ ! -d "samples/${samples_id}" ]; then
                echo "Sample directory 'samples/${samples_id}' does not exists."
                exit 9999
            fi
            