name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate samples index file
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: samples/schema.json
          INPUT_JSONS: samples/index.json
