name: Check samples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate JSON schema - index file
        run: jsonschema -i samples/index.json samples/schema.json

      - name: Validate samples
        run: bash ./.github/scripts/validate-samples.sh
